### ISSUE TITLE
Is there a way to do Automatic Persisted Queries with this toolkit?

### ISSUE THREAD

**Issue by stevector** [vladar/gatsby-graphql-toolkit#1]
Hi @vladar, 

@smthomas mentioned this repo in the weekly Drupal/Gatsby meeting. I'm curious if you have a recommendation for how to do Automatic Persisted Queries with WordPress and Drupal leveraging this toolkit. I work at Pantheon and I think we'll be able to show significant improvements in build times if the majority of queries are cachable in our CDN.

I've experimented with using Automatic Persisted Queries in WordPress using `gatsby-source-graphql` and https://github.com/Quartz/wp-graphql-persisted-queries by overriding `createLink:`

```
createLink: pluginOptions => {
   return createPersistedQueryLink({useGETForHashedQueries: true}).concat(createHttpLink({ uri: `https://${process.env.DATA_SOURCE_URL}/graphql`, fetch: fetch }))
}
```

It seemed to work but I'm looking for guidance from someone who knows more about GraphQL around best practices using these newer plugins.

**Comment by vladar** [comment]
Hey, thanks for reaching out!

The toolkit doesn't really care how you execute GraphQL queries. It just expects you to provide a function:
```js
execute({ query, operationName, variables })
```

that returns a standard GraphQL response (actually a Promise for this response):

```js
{
  data: {
    // response data
  },
  errors: []
}
```

You can use persisted queries or just send a full query. That is totally up to you.

We do provide a default implementation of such `execute` function but you can easily swap it with your own.

If you want you can use Apollo links inside this function:

```js
import { toPromise, execute as apolloExecute } from 'apollo-link';

const myApolloLink = createPersistedQueryLink({useGETForHashedQueries: true})
  .concat(createHttpLink({ uri: `https://${process.env.DATA_SOURCE_URL}/graphql`, fetch: fetch }))

async function execute({ query, operationName, variables }) {
  return toPromise(apolloExecute(myApolloLink , { query, operationName, variables }))
}
```

But as for me, apollo links introduce unnecessary overhead. Still, you can use them if you want.

**Comment by stevector** [comment]
Thanks @vladar! I see how I would set a custom `execute` when writing a source plugin using the toolkit. Do you expect that a site using your new `gatsby-source-drupal-graphql` would eventually be able to also override just the `execute` function from configuration?

**Comment by vladar** [comment]
I think yes. It makes sense to expose `execute` as an option. But it depends on how `gatsby-source-drupal-graphql ` plugin will be implemented. So it's up to the plugin author to decide (I will just prepare an initial prototype for this).

**Comment by stevector** [comment]
sounds good! thanks @vladar.
