### ISSUE TITLE
Select GraphQL errors thrown while creating source nodes

### ISSUE THREAD

**Issue by andris-sevcenko** [vladar/gatsby-graphql-toolkit#5]
While creating source nodes, a GraphQL error is thrown for some, but not all, node types

```
Failed to execute query LIST_faqs_faqs_Entry.
Errors:
Fragment "faqs_faqs_Entry" is never used.
```

The error is thrown when creating the pagination adapters:
`  - paginate.ts:60 Object.paginate
    [gatsby-source-craftcms]/[gatsby-graphql-source-toolkit]/src/source-nodes/fetch-nodes/paginate.ts:60:13`

I'm attaching the generated graphql document for that node.

[faqs_faqs_Entry.graphql.zip](https://github.com/vladar/gatsby-graphql-toolkit/files/5083709/faqs_faqs_Entry.graphql.zip)

Toolkit version: **0.30**

**Comment by vladar** [comment]
Should be fixed in `v0.3.1`. Probably hit some edge case in graphql `visitInParallel` but no time to dig into that at the moment. Thanks for reporting!
